const path = require('path');
const fs = require('fs-extra');

async function generateTypeDefinitions(queries) {

    const outputPath = path.resolve(__dirname, '../../index.d.ts');
    const keys = Object.keys(queries);
    const unionType = keys.length > 0 ?
        keys.map(k => `'${k}'`).join(' | ') + ' | (string & {})'
        : 'string';

    const content =
        `/**
* Auto-generated by QueryLock
* Do not edit manually.
*/

declare class QueryLock {
  constructor(config: any);
    
  init(): Promise<void>;
  refreshSchema(): Promise<void>;

  define(queryKey: QueryLock.QueryKey, ...args: QueryLock.FlexibleArgs): Promise<any>;

  read(queryKey: QueryLock.QueryKey, ...args: QueryLock.FlexibleArgs): Promise<any>;

  create(queryKey: QueryLock.QueryKey, ...args: QueryLock.FlexibleArgs): Promise<any>;

  update(queryKey: QueryLock.QueryKey, ...args: QueryLock.FlexibleArgs): Promise<any>;

  delete(queryKey: QueryLock.QueryKey, ...args: QueryLock.FlexibleArgs): Promise<any>;
}

declare namespace QueryLock {
  export type QueryKey = ${unionType};

  export type FlexibleArgs =
    | []
    | [string]
    | [object]
    | [string, object]
    | [object, string];
}

export = QueryLock;`

    try {
        await fs.writeFile(outputPath, content);
    } catch (err) {
        console.error('[QueryLock] Failed to generate type definitions:', err);
    }
}

module.exports = generateTypeDefinitions;