/**
* Auto-generated by QueryLock
* Do not edit manually.
*/

declare class QueryLock {
  constructor(config: any);
    
  init(): Promise<void>;
  refreshSchema(): Promise<void>;

  define(queryKey: QueryLock.QueryKey, ...args: QueryLock.FlexibleArgs): Promise<any>;

  read(queryKey: QueryLock.QueryKey, ...args: QueryLock.FlexibleArgs): Promise<any>;

  create(queryKey: QueryLock.QueryKey, ...args: QueryLock.FlexibleArgs): Promise<any>;

  update(queryKey: QueryLock.QueryKey, ...args: QueryLock.FlexibleArgs): Promise<any>;

  delete(queryKey: QueryLock.QueryKey, ...args: QueryLock.FlexibleArgs): Promise<any>;
}

declare namespace QueryLock {
  export type QueryKey = 'setup_schema' | 'seed_data' | 'get_top_spenders' | 'check_low_stock' | 'recent_orders' | (string & {});

  export type FlexibleArgs =
    | []
    | [string]
    | [object]
    | [string, object]
    | [object, string];
}

export = QueryLock;